### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by maxlorenz**

### CODE REVIEW

**Comment by maxlorenz** [comment]
@fabianbormann @tom3012 The landing page is currently and Markdown and needs (somehow) to be converted to an index.js. Is there a good way to automate that?

**Comment by tom3012** [comment]
Hmmm. I don't know if this is possible. My intention was to show a - let's say -  "fancy" landing page and I can't imagine that there is a markdown way to do that... I know the advantage of markdown in the case of documentation, news... But for the landing page I think there are only two options either easy editable or a fancy look...

**Comment by maxlorenz** [comment]
I'll have a look :)

**Comment by maxlorenz** [comment]
I updated the index.js with the new text :)

**Pull request merged**
